"""
Email composer and sender.
Uses SMTP (Gmail by default). Supports plain-text fallback.
"""
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timezone

from app.agent.schemas import AgentAnalysis, ExtractedEvent
from app.core.config import get_settings
from app.core.logging import get_logger

logger = get_logger(__name__)
settings = get_settings()

_DIRECTION_EMOJI = {
    "positive": "📈",
    "negative": "📉",
    "neutral":  "➡️",
}

_LABEL_COLOR = {
    "positive": "#16a34a",   # green
    "negative": "#dc2626",   # red
    "neutral":  "#d97706",   # amber
}


def _build_html(event: ExtractedEvent, analysis: AgentAnalysis) -> str:
    ticker      = event.primary_ticker or "Market"
    emoji       = _DIRECTION_EMOJI.get(analysis.final_label, "")
    color       = _LABEL_COLOR.get(analysis.final_label, "#374151")
    score_pct   = f"{analysis.final_score:.0%}"
    causal_html = "".join(
        f"<li style='margin-bottom:6px'>{step}</li>"
        for step in analysis.causal_chain
    )
    risk_html = "".join(
        f"<li style='margin-bottom:6px;color:#b45309'>{flag}</li>"
        for flag in analysis.risk_flags
    )
    market_rows = ""
    if event.primary_ticker:
        market_rows = f"""
        <tr><td style='padding:4px 8px;color:#6b7280'>Ticker</td>
            <td style='padding:4px 8px'><b>${ticker}</b></td></tr>
        <tr><td style='padding:4px 8px;color:#6b7280'>Event type</td>
            <td style='padding:4px 8px'>{event.event_type}</td></tr>
        <tr><td style='padding:4px 8px;color:#6b7280'>Sentiment</td>
            <td style='padding:4px 8px'>{event.sentiment_label} ({event.sentiment_score:.0%})</td></tr>
        <tr><td style='padding:4px 8px;color:#6b7280'>Novelty</td>
            <td style='padding:4px 8px'>{event.novelty_score:.0%}</td></tr>
        <tr><td style='padding:4px 8px;color:#6b7280'>Time horizon</td>
            <td style='padding:4px 8px'>{analysis.time_horizon}</td></tr>
        """

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""
<!DOCTYPE html>
<html>
<body style='font-family:Arial,sans-serif;max-width:640px;margin:auto;padding:24px;color:#111827'>

  <!-- Header -->
  <div style='background:{color};color:white;border-radius:8px;padding:20px 24px;margin-bottom:24px'>
    <div style='font-size:13px;opacity:0.85;margin-bottom:4px'>Finance News Alert &bull; {now}</div>
    <div style='font-size:26px;font-weight:700'>{emoji} ${ticker} &mdash; {analysis.final_label.upper()}</div>
    <div style='font-size:14px;margin-top:6px;opacity:0.9'>
      Confidence {score_pct} &bull; {analysis.time_horizon} horizon
    </div>
  </div>

  <!-- Summary -->
  <div style='background:#f9fafb;border-left:4px solid {color};padding:16px 20px;border-radius:4px;margin-bottom:24px'>
    <div style='font-size:13px;color:#6b7280;margin-bottom:6px;text-transform:uppercase;letter-spacing:.05em'>Summary</div>
    <div style='font-size:15px;line-height:1.6'>{analysis.user_readable_summary}</div>
  </div>

  <!-- Causal chain -->
  <div style='margin-bottom:24px'>
    <div style='font-size:13px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em;margin-bottom:10px'>Causal Chain</div>
    <ol style='margin:0;padding-left:20px;font-size:14px;line-height:1.7'>{causal_html}</ol>
  </div>

  <!-- Risk flags -->
  <div style='margin-bottom:24px'>
    <div style='font-size:13px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em;margin-bottom:10px'>Risk Flags</div>
    <ul style='margin:0;padding-left:20px;font-size:14px;line-height:1.7'>{risk_html}</ul>
  </div>

  <!-- Event metadata -->
  <div style='margin-bottom:24px'>
    <div style='font-size:13px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em;margin-bottom:10px'>Event Details</div>
    <table style='border-collapse:collapse;font-size:14px;width:100%'>
      {market_rows}
    </table>
  </div>

  <!-- Footer -->
  <div style='border-top:1px solid #e5e7eb;padding-top:16px;font-size:12px;color:#9ca3af'>
    Generated by Finance News Agent &bull; Powered by Claude (Anthropic)
  </div>

</body>
</html>
"""


def _build_plain(event: ExtractedEvent, analysis: AgentAnalysis) -> str:
    ticker = event.primary_ticker or "Market"
    causal = "\n".join(f"  {i+1}. {s}" for i, s in enumerate(analysis.causal_chain))
    risks  = "\n".join(f"  - {f}" for f in analysis.risk_flags)
    return f"""
FINANCE NEWS ALERT
==================
Ticker     : ${ticker}
Label      : {analysis.final_label.upper()}
Confidence : {analysis.final_score:.0%}
Horizon    : {analysis.time_horizon}
Event      : {event.event_type}

SUMMARY
-------
{analysis.user_readable_summary}

CAUSAL CHAIN
------------
{causal}

RISK FLAGS
----------
{risks}

---
Generated by Finance News Agent | Powered by Claude (Anthropic)
""".strip()


class EmailSender:
    def __init__(
        self,
        recipient: str,
        smtp_host: str | None = None,
        smtp_port: int | None = None,
        smtp_user: str | None = None,
        smtp_password: str | None = None,
    ):
        self.recipient  = recipient
        self.smtp_host  = smtp_host     or settings.smtp_host
        self.smtp_port  = smtp_port     or settings.smtp_port
        self.smtp_user  = smtp_user     or settings.smtp_user
        self.smtp_pass  = smtp_password or settings.smtp_password

    def send(self, event: ExtractedEvent, analysis: AgentAnalysis) -> bool:
        ticker  = event.primary_ticker or "Market"
        emoji   = _DIRECTION_EMOJI.get(analysis.final_label, "")
        subject = (
            f"{emoji} [{ticker}] {analysis.final_label.upper()} "
            f"({analysis.final_score:.0%}) — {event.event_type}"
        )

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = self.smtp_user
        msg["To"]      = self.recipient

        msg.attach(MIMEText(_build_plain(event, analysis), "plain"))
        msg.attach(MIMEText(_build_html(event, analysis),  "html"))

        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.ehlo()
                server.starttls()
                server.login(self.smtp_user, self.smtp_pass)
                server.sendmail(self.smtp_user, self.recipient, msg.as_string())

            logger.info(
                "email_sender.sent",
                to=self.recipient,
                subject=subject,
                ticker=ticker,
            )
            return True

        except Exception as e:
            logger.error("email_sender.failed", error=str(e), to=self.recipient)
            return False
